# Generated by Django 5.2.4 on 2025-07-19 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bidang', models.CharField(choices=[('AST', 'Astronomi'), ('BIO', 'Biologi'), ('EKO', 'Ekonomi'), ('FIS', 'Fisika'), ('GEO', 'Geografi'), ('INF', 'Informatika'), ('KBM', 'Kebumian'), ('KIM', 'Kimia'), ('MAT', 'Matematika')], max_length=3)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('duration', models.IntegerField(help_text='duration in seconds')),
                ('user_start', models.DateTimeField()),
                ('user_end', models.DateTimeField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
