services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: sparing_mingguan_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=500"]
    networks:
      - backend_net

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend_net

volumes:
  postgres_data:

networks:
  backend_net:
